Customer Database Methods
Sparkling-Barracudas/Sprint2 pull request #19
Opened 2022-02-27 05:14 UTC by jarell38

A new class made to add a customer order into the databse with the createOrder method which also calls the update product method to update the product quantity after an order (Not completely sure the code works just wanted you guys to check it out)

2022-02-27 05:30 UTC, FrankFerrer1 requested changes
I don't see a change in the driver class to implement this

2022-02-28 02:26 UTC, ajminer0913 approved these changes
Looks good; I mean I know we are planning on updating methods later!

2022-02-28 04:11 UTC, FrankFerrer1 approved these changes

2022-02-28 04:14 UTC, nkauffm1 approved these changes
It works!

2022-02-28 04:14 UTC, merged